language: node_js

node_js:
- '0.11'
- '0.10'

before_script:
- npm install -g grunt-cli

after_script:
- grunt coveralls

env:
  global:
  - secure: PwXSzt5h9NwD+5gmdqryeJBw1lSxh2Pge3AHJPmMZ02BA/NPFHwRAooVzI+LbFb9BMAvFNkuts/MhzYB7ZXLwpQR3ERWFQQIHR2uczJOt1yy2HpuOKPHUf1hYOtSvcJ64BnDFrA5Cc45Zy5O02BJPWRj1QPYB/vJAFFlmNjWh3U=
  - secure: enpRjHuwM36qNoQ89BFqIo5j7vBM+XKntPKxphKmeOjHoYjL4T21VuR7sOseSaSV36PYiSoBMdd9j7nQcUabm1sOA4Zhuf38gkNbzzIdSUVhofFiEQG1DzJFw0cgKAM1sagLJ/jfpcQQdcNQcBVe+22f+n+st8tofSziMhPa624=
