language: node_js

node_js:
- '0.11'
- '0.10'

before_script:
- npm install -g grunt-cli

after_script:
- grunt coveralls

env:
  global:
  - secure: bx1tEo4UITH7u7pjWIyR8zOKWvkX3APz0mW30PVdGuXCeCmHg/KIq6VRAenn+UTfTfQvImShwY42RYfg7tsYw5PWWGIzzjAhHqJhzFbzeFNQjdOzcZcUrmHKZkIcx19vr20OpkgNUZVucLlxg6MeUzUqTDy1KOg/vMwPuw9/ch0=
  - secure: L/wSFUAKOp1okFimlYlN+ib/Ruwz+KbTpOjdYJug1WbJIC1wH2IZ6ctftWnjkbqDNf49ydiCn9L1+y0yssGLyDMWhfe7sEZ4savcrt7qXPEcIJ6R96CvqvTXPY68LP23riegN63evNRE2Y3vrYxbBVpd0xCUcFa1MccqnJDgbjc=
